ALTER TABLE move DROP COLUMN timestamp;
ALTER TABLE move ADD timestamp TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE game DROP COLUMN started_at;
ALTER TABLE game ADD started_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE game DROP COLUMN last_move_at;
ALTER TABLE game ADD last_move_at TIMESTAMP WITHOUT TIME ZONE;
