server:
  port: 8000
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "OPTIONS"
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
